author: "Hao-Ting Wang, Steven L Meisler, Hanad Sharmarke, Natasha Clarke, Nicolas\
  \ Gensollen, Christopher J Markiewicz, Fran\xE7ois Paugam, Bertrand Thirion, Pierre\
  \ Bellec"
bibtex_bibfiles:
- references.bib
copyright: '2023'
execute:
  execute_notebooks: force
  timeout: -1
html:
  use_issues_button: false
  use_repository_button: true
latex:
  latex_documents:
    targetname: book.tex
launch_buttons:
  binderhub_url: https://binder-mcgill.conp.cloud
  notebook_interface: classic
  thebe: false
logo: logo.png
only_build_toc_files: true
repository:
  branch: main
  path_to_book: content
  url: https://github.com/roboneurolibre/fmriprep-denoise-benchmark
sphinx:
  config:
    bibtex_reference_style: author_year
title: A reproducible benchmark of denoising strategies in resting-state fMRI connectivity
  using fMRIPrep and Nilearn
